#target illustrator
#targetengine "3flab-duplicate_items"
app.preferences.setBooleanPreference('ShowExternalJSXWarning', false);
eval("""@JSXBIN@ES@2.0@MyBbyBnABMLbyBn0AHJMnABXzJjTjFjMjFjDjUjJjPjOBfjzDjEjPjDCfnbfJNnAS
zDjBjSjSDAAnnftJOnASzDjHjSjPEBEXzDjBjEjEFfXzKjHjSjPjVjQiJjUjFjNjTGfXzFjMjBjZjFj
SHfXzBhQIfVzEjTjFjMjTJfGnfnftaPbQn0AFJQnASzDjPjCjKKDWzGiPjCjKjFjDjULAnftJRnASzD
jTjFjMMEQzANfVJfGVzBjJOfCnftJSnABXzHjPjSjJiJjUjFjNPfVKfDVMfEnfJTnABXzHjEjVjQiJj
UjFjNQfVKfDEXzJjEjVjQjMjJjDjBjUjFRfVMfERCVEfBXzGiJiOiTiJiEiFSfjzQiFjMjFjNjFjOjU
iQjMjBjDjFjNjFjOjUTfffnfJUnAEXzEjQjVjTjIUfVDfARBVKfDffAVOfCAXzGjMjFjOjHjUjIVfVJ
fGByBzBhcWJWnABXzIjTjFjMjFjDjUjFjEXfVEfBnctfaXbYn0ACJYnASzDjUjBjSYFQNfVDfAVOfCn
ftJZnAEXzEjNjPjWjFZfXQfVYfFRCXPfVYfFXzLiQiMiBiDiFiCiFiGiPiSiFgafjTfffAVOfCAXVfV
DfAByBWJgbnAEXzGjSjFjNjPjWjFgbfVEfBnfAHO4C0AiAJ40BhAD40BiAE4B0AiAK4D0AiAM4E0AiA
Y4F0AiABGAzDjEjVjQgcAgcBOCbDn0ADJDnASCyBXzOjBjDjUjJjWjFiEjPjDjVjNjFjOjUgdfjzDjB
jQjQgefnftJEnASJyBXBfVCfyBnftOFbyHn0ABJHnAEjgcfRBVJfyBffAUzChGhGgfCzBhehAXVfVJf
yBnndACzDhBhdhdhBXzIjUjZjQjFjOjBjNjFhCfVJfyBnneJiUjFjYjUiSjBjOjHjFnnnAChAXVfjzJ
jEjPjDjVjNjFjOjUjThDfnndAnACJ4B0AiAC40BiAACANByB""");